### PR TITLE
Update project structure

### PR DESCRIPTION
**Pull request by iillyyaa2033**
This PR changes structure of project to follow modern Android development practices:
- shell buildscript replaced gradle build system + .gradle configs;
- entire project has been split into two subprojects: `library` (contains `XServer` and all related resources) and `demo` (from `XDemo`);
- also I've reformatted all code and some comments because current code formatting looks really weird.

So with this PR applied you can just open this project with Android Studio and everything will work out-of-the-box.

### CODE REVIEW

**Comment by nwrkbiz** [comment]
I am fine with this, as I do not have any android studio/gardle experience.

**Comment by iillyyaa2033** [comment]
Sure you can, but:
- it'll cost you some time to rewrite buildscript right now and you'll have to rewrite it again and again when something changes in project structure or in project's dependencies;
- gradle allows building the project with vanilla debian packages too: you just need Java and Android SDK installed;
- I'm planning to publish `library` subproject as Maven artifact on bintray (it'll very useful to anyone who wants to embed library in own project), this can be done rather easy using `com.novoda.bintray-release` gradle plugin but I have no clue how to do it using makefile without pain and suffering.

Of course gradle has some flaws: if you dont have system-wide `gradle` and using `./gradlew` from project folder, it'll load at first launch about 150mb of own build tools, but I think this is reasonable price for such convenience.

**Comment by nwrkbiz** [comment]
Ok, then I'll try to educate myself and start using gradle. Is there a way to add a assets folder using this build system (Without the need to install Android Studio)? I use this project to launch some of my  C++ FLTK programs and for this I usually copy the binaries to the assets folder. (Maybe you know a better trick?)

**Comment by iillyyaa2033** [comment]
Another approach to run binaries on Android is to compie them into shared library and communicate with them via JNI. But I'm not sure that it is better trick because JNI is complicated on C side.

As for `assets/` folder within `.apk` file, you can simply create `assets/` folder near the `res/`. All files from here will be copied into corresponding folder in `.apk`.
<details>
<summary>Click here to see screenshot</summary>

image
</details>

**Comment by nwrkbiz** [comment]
Ok thanks, I already messed around with the jni stuff, but for my current project i really just want to execute a normal elf executable. (I basically wrap this XServer around my binary and start it using the java processbuilder)

I will close this pr now (:

**Pull request merged**
